name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"     # runs every midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: TheekHainBhai
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push snake animation to output branch
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "ğŸ update snake animation"
          add: "dist/*"
          branch: output          # <----- THIS is what makes it work
